// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW4enhKp39h7c7o2S5eYdPzErE0yvgaXM',
    appId: '1:170516284368:web:a0c9908cbf2720f4906fd5',
    messagingSenderId: '170516284368',
    projectId: 'revive-app-d8d70',
    authDomain: 'revive-app-d8d70.firebaseapp.com',
    storageBucket: 'revive-app-d8d70.appspot.com',
    measurementId: 'G-RD78CFG6EE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiZEGS1pixeMmuBkJ3AMewi1dDAzyI8l8',
    appId: '1:170516284368:android:855c6222f62664d1906fd5',
    messagingSenderId: '170516284368',
    projectId: 'revive-app-d8d70',
    storageBucket: 'revive-app-d8d70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVuW0xQ7nMbuFqvk3InoQmn9BjsNyQvR0',
    appId: '1:170516284368:ios:cbd994b13d29c54f906fd5',
    messagingSenderId: '170516284368',
    projectId: 'revive-app-d8d70',
    storageBucket: 'revive-app-d8d70.appspot.com',
    iosBundleId: 'com.example.blood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVuW0xQ7nMbuFqvk3InoQmn9BjsNyQvR0',
    appId: '1:170516284368:ios:cbd994b13d29c54f906fd5',
    messagingSenderId: '170516284368',
    projectId: 'revive-app-d8d70',
    storageBucket: 'revive-app-d8d70.appspot.com',
    iosBundleId: 'com.example.blood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDW4enhKp39h7c7o2S5eYdPzErE0yvgaXM',
    appId: '1:170516284368:web:21092337818d7047906fd5',
    messagingSenderId: '170516284368',
    projectId: 'revive-app-d8d70',
    authDomain: 'revive-app-d8d70.firebaseapp.com',
    storageBucket: 'revive-app-d8d70.appspot.com',
    measurementId: 'G-R2HZE2X40B',
  );

}